### ISSUE TITLE
Spyder IPython console won't open

### ISSUE THREAD

**Issue by gitperson** [spyder-ide/website#1]
After installing Python xy and working with Spyder for some time now, suddenly, upon opening Spyder, I am getting an error message "An error ocurred while starting the kernel". I've tried opening a new iPython console, but this produces the same error. I've tried resetting Spyder and even uninstalling and installing python xy multiple times, but the same error occurs. 

Can anyone advise me on how to identify and fix the problem? These problems are bewildering to me and I haven't been able to dig up the solution in my searches. The full error message is below:

An error ocurred while starting the kernel
                                                                           
OperationalError Traceback (most recent call last)
C:\Python27\lib\site packages\spyderlib\widgets\externalshell\start_ipython_kernel.py in ()
168 ipk_temp = IPKernelApp.instance()
169 ipk_temp.config = kernel_config()
  > 170 ipk_temp.initialize()
global ipk_temp.initialize = >
171 
172 # Grabbing the kernel's shell to share its namespace with our

C:\Python27\lib\site packages\IPython\kernel\zmq\kernelapp.pyc in initialize(self=, argv=None)

C:\Python27\lib\site packages\IPython\config\application.pyc in catch_config_error(method=, app=, *args=(None,), **kwargs={})
90 """
91 try:
   > 92 return method(app, *args, **kwargs)
method = 
app = 
args = (None,)
kwargs = {}
93 except (TraitError, ArgumentError) as e:
94 app.print_help()

C:\Python27\lib\site packages\IPython\kernel\zmq\kernelapp.pyc in initialize(self=, argv=None)
440 self.init_io()
441 self.init_signal()
  > 442 self.init_kernel()
self.init_kernel = >
443 # shell init steps
444 self.init_path()

C:\Python27\lib\site packages\IPython\kernel\zmq\kernelapp.pyc in init_kernel(self=)
395 log=self.log,
396 profile_dir=self.profile_dir,
  > 397 user_ns=self.user_ns,
global user_ns = undefined
self.user_ns = None
398 )
399 kernel.record_ports(self.ports)

C:\Python27\lib\site packages\IPython\kernel\zmq\ipkernel.pyc in __init__(self=, **kwargs={'iopub_socket': , 'log': , 'parent': , 'profile_dir': , 'session': , 'shell_streams': [, ], 'stdin_socket': , 'user_ns': None})
143 user_module = self.user_module,
144 user_ns = self.user_ns,
  > 145 kernel = self,
global kernel = undefined
self = 
146 )
147 self.shell.displayhook.session = self.session

C:\Python27\lib\site packages\IPython\config\configurable.pyc in instance(cls=, *args=(), **kwargs={'kernel': , 'parent': , 'profile_dir': , 'user_module': None, 'user_ns': None})
352 # Create and save the instance
353 if cls._instance is None:
  > 354 inst = cls(*args, **kwargs)
inst = undefined
cls = 
args = ()
kwargs = {'kernel': , 'user_ns': None, 'profile_dir': , 'parent': , 'user_module': None}
355 # Now make sure that the instance will also be returned by
356 # parent classes' _instance attribute.

C:\Python27\lib\site packages\IPython\core\interactiveshell.pyc in __init__(self=, ipython_dir=None, profile_dir=, user_module=None, user_ns=None, custom_exceptions=((), None), **kwargs={'kernel': , 'parent': })
463 self.db = PickleShareDB(os.path.join(self.profile_dir.location, 'db'))
464 
  > 465 self.init_history()
self.init_history = >
466 self.init_encoding()
467 self.init_prefilter()

C:\Python27\lib\site packages\IPython\core\interactiveshell.pyc in init_history(self=)
1519 def init_history(self):
1520 """Sets up the command history, and starts regular autosaves."""
 > 1521 self.history_manager = HistoryManager(shell=self, parent=self)
self.history_manager = None
global HistoryManager = 
global shell = undefined
self = 
global parent = undefined
1522 self.configurables.append(self.history_manager)
1523 

C:\Python27\lib\site packages\IPython\core\history.pyc in __init__(self=, shell=, config=None, **traits={'parent': })
496 self.save_thread.start()
497 
  > 498 self.new_session()
self.new_session = >
499 
500 def _get_hist_file_name(self, profile=None):

C:\Python27\lib\site packages\IPython\core\history.pyc in new_session(self=, conn=None)

C:\Python27\lib\site packages\IPython\core\history.pyc in needs_sqlite(f=, self=, *a=(None,), **kw={})
66 return []
67 else:
   > 68 return f(self, *a, **kw)
f = 
self = 
a = (None,)
kw = {}
69 
70 

C:\Python27\lib\site packages\IPython\core\history.pyc in new_session(self=, conn=)
514 with conn:
515 cur = conn.execute("""INSERT INTO sessions VALUES (NULL, ?, NULL,
  > 516 NULL, "") """, (datetime.datetime.now(),))
global NULL = undefined
global Close = undefined
global the = undefined
global database = undefined
global session = undefined
global filling = undefined
global end = undefined
global time = undefined
global line = undefined
global count.UPDATE = undefined
global sessions = undefined
global SET = undefined
global num_cmds = undefined
global WHERE = undefined
517 self.session_number = cur.lastrowid
518 

OperationalError: attempt to write a readonly database

**Comment by ccordoba12** [comment]
This is not the right place to open issues for Spyder. Please open it here

https://github.com/spyder-ide/spyder/issues

But seeing your error, it seems the problem you have is related to IPython not being able to save its history of commands.

Look for a directory called `.ipython` in your user directory, remove it, and be sure that it's possible to write content there. That should fix your problem.
